"""bucket file connection table is created

Revision ID: 5fd05e9d693f
Revises: c34f378fc506
Create Date: 2026-09-19 20:36:47.885959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '5fd05e9d693f'
down_revision: Union[str, Sequence[str], None] = 'c34f378fc506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_file',
    sa.Column('bucket_file_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('bucket_key', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'spread_sheat', name='bucketfiletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repo_file.file_id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('bucket_file_id'),
    sa.UniqueConstraint('repo_id', 'file_id', 'url', name='repo_file_url_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucket_file')
    # ### end Alembic commands ###
