"""added tables for chat storage and user connectivity

Revision ID: 6ab5c4b0e55b
Revises: 0edb31946672
Create Date: 2026-09-22 16:55:51.269460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '6ab5c4b0e55b'
down_revision: Union[str, Sequence[str], None] = '0edb31946672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repo',
    sa.Column('user_repo_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_repo_id')
    )
    op.create_table('chat',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_repo_id', sa.UUID(), nullable=False),
    sa.Column('chat_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_repo_id'], ['user_repo.user_repo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('conversation',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('models', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('LIKE', 'DISLIKE', 'NONE', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('chat_source',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('embed_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.ForeignKeyConstraint(['embed_id'], ['embedding.embed_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.drop_index(op.f('idx_embedding_chunk_str_trgm'), table_name='embedding', postgresql_ops={'chunk_str': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('file_import', 'module',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('file_import', 'resolved_path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_import', 'resolved_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('file_import', 'module',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('idx_embedding_chunk_str_trgm'), 'embedding', ['chunk_str'], unique=False, postgresql_ops={'chunk_str': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table('chat_source')
    op.drop_table('conversation')
    op.drop_table('chat')
    op.drop_table('user_repo')
    # ### end Alembic commands ###
