"""create table retry

Revision ID: c34f378fc506
Revises: e9cc21670bd8
Create Date: 2026-09-16 17:37:49.818668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'c34f378fc506'
down_revision: Union[str, Sequence[str], None] = 'e9cc21670bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(length=110), nullable=False),
    sa.Column('repo_full_name', sa.String(length=210), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('license', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('owner_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'processing', 'failed', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('repo_id'),
    sa.UniqueConstraint('repo_full_name'),
    sa.UniqueConstraint('repo_url')
    )
    op.create_table('repo_file',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_ext', sa.Text(), nullable=False),
    sa.Column('file_category', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'rejected', 'processing', 'canceled', name='fileprocess'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('repo_id', 'file_path', name='uq_repo_file_repo_id_file_path')
    )
    op.create_table('dependencies',
    sa.Column('dep_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repo_file.file_id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('dep_id')
    )
    op.create_table('embedding',
    sa.Column('embed_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('chunk', sa.JSON(), nullable=False),
    sa.Column('chunk_str', sa.Text(), nullable=False),
    sa.Column('vector', Vector(384), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repo_file.file_id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('embed_id')
    )
    op.create_table('file_import',
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('imported_file_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('module_alias', sa.Text(), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('file_type', sa.Enum('INTERNAL', 'EXTERNAL', 'STDLIB', name='file_type_name'), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('resolved_path', sa.Text(), nullable=False),
    sa.Column('is_static', sa.Boolean(), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repo_file.file_id'], ),
    sa.ForeignKeyConstraint(['imported_file_id'], ['repo_file.file_id'], ),
    sa.PrimaryKeyConstraint('import_id')
    )
    op.create_table('ingest_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repo_file.file_id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('repo_dep_details',
    sa.Column('detail_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['repo_file.file_id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('detail_id'),
    sa.UniqueConstraint('repo_id', 'file_id', name='uq_repo_dep_repo_file')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_dep_details')
    op.drop_table('ingest_logs')
    op.drop_table('file_import')
    op.drop_table('embedding')
    op.drop_table('dependencies')
    op.drop_table('repo_file')
    op.drop_table('repository')
    # ### end Alembic commands ###
