name: Ingest Repository

on:
  repository_dispatch:
    types: [start-ingest]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set GITHUB_URL variable
        run: |
          echo "GITHUB_URL=${{ github.event.client_payload.github_url }}" >> $GITHUB_ENV

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: "uv"

      - name: Setup Python
        run: uv python install

      - name: Cache Machine Learning Models & Binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/fastembed
            ~/.cache/huggingface
            ~/.cache/docling
            ~/.cache/pypandoc
            ~/.local/bin/pandoc
          key: ${{ runner.os }}-models-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-models-

      - name: Sync Deps using UV
        run: |
         cd backend
         uv sync --frozen

      - name: Download PyPandoc
        run: |
         cd backend
         uv run python -c "import pypandoc; pypandoc.download_pandoc()"

      - name: Run Ingest File
        env:
          PYTHONPATH: .
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SPREADSHEAT_BUCKET_NAME: ${{ secrets.SPREADSHEAT_BUCKET_NAME }}
          IMAGE_BUCKET_NAME: ${{ secrets.IMAGE_BUCKET_NAME }}
        run: |
         cd backend
         uv run python app/scripts/run_ingest.py